package key

import (
	"crypto/tls"
	"fmt"
	"github.com/btcsuite/btcd/btcutil"
	"github.com/stretchr/testify/assert"
	"testing"
	"time"
)

func TestNewKeyPair(t *testing.T) {
	org := "btc-wallet autogenerated cert"
	validUntil := time.Now().Add(time.Hour * 24 * 365 * 10)
	cert, key, err := btcutil.NewTLSCertPair(org, validUntil, nil)
	assert.NoError(t, err)
	fmt.Printf("cert = %v\n", cert)
	fmt.Printf("key = %v\n", key)

	keyPair, err := tls.X509KeyPair(cert, key)
	assert.NoError(t, err)
	fmt.Printf("keyPair = %v\n", keyPair)
}
